<script setup>
import DigitalSensingProductsColumn from "./components/DigitalSensingProductsColumn.vue";
import AppsHubsColumn from "./components/AppsHubsColumn.vue";
import CentralizedColumn from "./components/CentralizedColumn.vue";
import ManufacturersColumn from "./components/ManufacturersColumn.vue";
import FilteringStorageColumn from "./components/FilteringStorageColumn.vue";
import AnalyticsQueryingColumn from "./components/AnalyticsQueryingColumn.vue";
import DividerArrow from "./components/partials/DividerArrow.vue";
import NavigationStep from "./components/partials/NavigationStep.vue";</script>
<template>

	<main id="app-wrap">
		<div class="">
			<nav class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8" aria-label="Progress">
				<ol role="list"
				    class="overflow-hidden lg:flex">

					<NavigationStep :status="stepStatus(1)" title="Getting Started"
					                desc="A few questions to help you get started" :sep="false"
					                :step="1" @click="stepNav(1)"/>
					<NavigationStep :status="stepStatus(2)" title="Design"
					                desc="Customize your Sensor Data slide." :step="2"
					                @click="stepNav(2)"/>
					<NavigationStep :status="stepStatus(3)" title="Finish"
					                desc="Download your customized slide." :step="3"
					                @click="stepNav(3)"/>

				</ol>
			</nav>
		</div>

		<div id="slide-design" class="aspect-video h-full py-16 px-12 bg-gray-50">

			<fieldset
			    v-if="currentStep === 1"
			    class="w-3/6 h-full flex flex-col justify-center mx-auto">

				<div class="flex items-start py-6 mb-2 border-b border-gray-200">
					<div class="mr-4 text-sm">
						<span class="font-medium text-gray-700">
							Does your digital sensing product require an App or Hub to
							transmit data from the measurement tool to you?
						</span>
						<p>
							<button @click="showInfo(1)"
							        class="font-normal text-gray-400 underline hover:text-brand-dark hover:no-underline"
							        v-if="!isInfoShown(1)">I don't know...
							</button>
						</p>
						<div v-if="isInfoShown(1)" class="mt-3 text-gray-500">
							<p>
								To map your sensor data flow, you need to know whether
								an App or Hub is required to transmit data.
							</p>
							<ul role="list" class="list-disc ml-4">
								<li>Contact your vendor partner to determine if an App
									or Hub is required
								</li>
								<li>Learn more about the sensor data measurement system
									starting <a
									    href="https://docs.google.com/presentation/d/1vBEa_ZBhutOCAVVZ2z5Qq8xG2uQ3y2B61LwMUQPJnmw/edit#slide=id.gccf2994462_0_1265"
									    target="_blank">here</a> in <a
									    href="https://playbook.dimesociety.org/"
									    target="_blank">The Playbook</a>.
								</li>
								<li>Plan for action item linking to work generated by
									this project that is not yet complete
								</li>
							</ul>
						</div>
					</div>
					<div class="flex mt-0.5">
						<div class="space-y-2">
							<div class="flex items-center">
								<input id="apphubtrue"
								       type="radio"
								       aria-describedby="Add App and Hub Column"
								       :checked="isColumnShown('apphub')"
								       @click="addColumn('apphub')"
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="apphubtrue"
								       class="ml-1 block text-sm font-medium text-gray-700">
									Yes </label>
							</div>
							<div class="flex items-center">
								<input id="apphubfalse"
								       type="radio"
								       :checked="!isColumnShown('apphub')"
								       @click="removeColumn('apphub')"
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="apphubfalse"
								       class="ml-1 block text-sm font-medium text-gray-700">
									No </label>
							</div>
						</div>
					</div>
				</div>
				<div class="flex items-start py-6 mb-2  border-b border-gray-200">
					<div class="mr-4 text-sm">
						<span class="font-medium text-gray-700">
							Does data generated by your digital sensing product flow through
							servers belonging to the manufacturer of the measurement tool?
						</span>
						<p>
							<button @click="showInfo(2)"
							        class="font-normal text-gray-400 underline hover:text-brand-dark hover:no-underline"
							        v-if="!isInfoShown(2)">I don't know...
							</button>
						</p>
						<div v-if="isInfoShown(2)" class="mt-3 text-gray-500">
							<p>
								To map your sensor data flow, you need to know whether
								the manufacturer of your digital sensing product
								requires that the data flows through their servers.
							</p>
							<ul role="list" class="list-disc ml-4">
								<li>
									Contact your vendor partner to determine if the
									sensor generated data must flow through the
									manufacturers’ servers
								</li>
								<li>
									Learn more about the sensor data measurement
									system
									starting <a
								    href="https://docs.google.com/presentation/d/1vBEa_ZBhutOCAVVZ2z5Qq8xG2uQ3y2B61LwMUQPJnmw/edit#slide=id.gccf2994462_0_1265"
								    target="_blank">here</a> in <a
								    href="https://playbook.dimesociety.org/"
								    target="_blank">The Playbook</a>.
								</li>
								<li>
									Plan for action item linking to work generated
									by
									this project that is not yet complete
								</li>
							</ul>
						</div>
					</div>
					<div class="flex mt-0.5">
						<div class="space-y-2">
							<div class="flex items-center">
								<input id="manufacturertrue" name="manufacturer"
								       type="radio"
								       aria-describedby="Add Manufacturer's Servers"
								       :checked="isColumnShown('manufacturer')"
								       @click="addColumn('manufacturer')"
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="manufacturertrue"
								       class="ml-1 block text-sm font-medium text-gray-700">
									Yes </label>
							</div>
							<div class="flex items-center">
								<input id="manufacturerfalse" name="manufacturer"
								       type="radio"
								       :checked="!isColumnShown('manufacturer')"
								       @click="removeColumn('manufacturer')"
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="manufacturerfalse"
								       class="ml-1 block text-sm font-medium text-gray-700">
									No </label>
							</div>
						</div>
					</div>
				</div>
				<div class="flex items-start py-4 mb-4">
					<div class="mr-4 text-sm">
						<span class="font-medium text-gray-700">
							Does the data consumer perform filtering on the sensor generated
							data and store the data internally prior to performing analytics
							on the data and querying it?
						</span>
						<p>
							<button @click="showInfo(3)"
							        class="font-normal text-gray-400 underline hover:text-brand-dark hover:no-underline"
							        v-if="!isInfoShown(3)">I don't know...
							</button>
						</p>
						<div v-if="isInfoShown(3)" class="mt-3 text-gray-500">
							<p>
								To map your sensor data flow, you need to know whether
								the data consumer will perform filtering on the sensor
								generated data and store the data locally.
							</p>
							<ul role="list" class="list-disc ml-4">
								<li>Contact your vendor partner to determine if the
									sensor generated data must flow through the
									manufacturers’ servers
								</li>
								<li>Learn more about the sensor data measurement system
									starting <a
									    href="https://docs.google.com/presentation/d/1vBEa_ZBhutOCAVVZ2z5Qq8xG2uQ3y2B61LwMUQPJnmw/edit#slide=id.gccf2994462_0_1265"
									    target="_blank">here</a> in <a
									    href="https://playbook.dimesociety.org/"
									    target="_blank">The Playbook</a>.
								</li>
								<li>Plan for action item linking to work generated by
									this project that is not yet complete
								</li>
							</ul>
						</div>
					</div>
					<div class="flex mt-0.5">
						<div class="space-y-2">
							<div class="flex items-center">
								<input id="analyticstrue" name="analytics"
								       type="radio"
								       aria-describedby="Add Manufacturer's Servers"
								       :checked="isColumnShown('analytics')"
								       @click="addColumn('analytics')"
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="analyticstrue"
								       class="ml-1 block text-sm font-medium text-gray-700">
									Yes </label>
							</div>
							<div class="flex items-center">
								<input id="analyticsfalse" name="analytics"
								       type="radio"
								       :checked="!isColumnShown('analytics')"
								       @click="removeColumn('analytics')"
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="analyticsfalse"
								       class="ml-1 block text-sm font-medium text-gray-700">
									No </label>
							</div>
						</div>
					</div>
				</div>
				<div class="flex flex-initial">
					<button @click="stepNav(2)"
					        class="bg-brand border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-brand-light focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand">
						Continue
					</button>
				</div>

			</fieldset>

			<div
			    v-if="currentStep === 2"
			    class="grid grid-flow-col auto-cols-max justify-evenly gap-0 h-full">
				<DigitalSensingProductsColumn/>
				<DividerArrow v-if="isColumnShown('apphub')"/>
				<AppsHubsColumn v-if="isColumnShown('apphub')"/>
				<DividerArrow/>
				<CentralizedColumn class="col-span-2"/>
				<DividerArrow v-if="isColumnShown('manufacturer')"/>
				<ManufacturersColumn class="col-span-2" v-if="isColumnShown('manufacturer')"/>
				<DividerArrow/>
				<FilteringStorageColumn/>
				<DividerArrow v-if="isColumnShown('analytics')"/>
				<AnalyticsQueryingColumn v-if="isColumnShown('analytics')"/>

			</div>

			<div v-if="currentStep === 3">
				<div class="text-right">

					<a
					    :href="generatedImage"
					    download="dme-slide.png"
					    class="mb-6 no-underline bg-brand border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-brand-light focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand">
						Download Slide
					</a>

					<img :src="generatedImage" alt="Your DME Image" class="border
					     border-gray-200 rounded-sm shadow-sm ring-4 ring-offset-2
					     ring-offset-gray-50 ring-gray-100">

				</div>
				TODO: Show Image and Download Button

				<p>
					Testing Info:
				</p>
				<p>

					{{ currentStep }}
					{{ shownInfo }}
					{{ columnOptions }}

				</p>
			</div>
		</div>

	</main>


</template>

<script>

import domtoimage from "dom-to-image-more";

export default {
	name: 'DME App',
	data() {
		return {
			currentStep: 1,
			shownInfo: 0,
			columnOptions: [],
			generatedImage: '',
			capturing: false,
		};
	},
	props: {},
	methods: {
		isInfoShown: function (step) {
			return this.shownInfo === step;
		},
		showInfo: function (step) {
			this.shownInfo = step;
		},
		setImage: function (dataUrl) {
			this.generatedImage = dataUrl;
		},
		filterForDomImage: function (node) {
			if (node.classList) return !node.classList.contains("icon-drawer");
			return true;
		},
		stepNav: function (step) {
			if (step === 3) {
				if ( this.currentStep === 1 ) {
					return this.currentStep = 2;
				}
				this.capturing = true;
				domtoimage
				    .toPng(document.getElementById('slide-design'), {filter: this.filterForDomImage})
				    .then((dataUrl) => {
					    this.setImage(dataUrl);
					    this.capturing = false;
					    this.currentStep = 3;
				    })
				    .catch(function (error) {
					    this.capturing = false;
					    console.error('oops, something went wrong!', error);
					    this.currentStep = 2;
				    });
				return;
			}
			this.currentStep = step
		},
		isColumnShown: function (columnKey) {
			console.log(this.columnOptions.includes(columnKey))
			return this.columnOptions.includes(columnKey);
		},
		addColumn: function (columnKey) {
			if (this.columnOptions.includes(columnKey)) {
				return true;
			}
			this.columnOptions.push(columnKey);
		},
		removeColumn: function (columnKey) {
			if (!this.columnOptions.includes(columnKey)) {
				return false;
			}
			let i = this.columnOptions.indexOf(columnKey);
			if (i > -1) {
				this.columnOptions.splice(i, 1);
			}
		},
		stepStatus: function (step) {

			if (step === this.currentStep) {
				return 'current'
			}

			// check if completed
			if (this.currentStep > step) {
				return 'completed'
			}

			return 'upcoming'
		}
	},
}
</script>
