<script setup>
import DigitalSensingProductsColumn from "./components/DigitalSensingProductsColumn.vue";
import AppsHubsColumn from "./components/AppsHubsColumn.vue";
import CentralizedColumn from "./components/CentralizedColumn.vue";
import ManufacturersColumn from "./components/ManufacturersColumn.vue";
import FilteringStorageColumn from "./components/FilteringStorageColumn.vue";
import AnalyticsQueryingColumn from "./components/AnalyticsQueryingColumn.vue";
import DividerArrow from "./components/partials/DividerArrow.vue";
import NavigationStep from "./components/partials/NavigationStep.vue";</script>
<template>

	<main id="app-wrap">
		<div class="">
			<nav class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8" aria-label="Progress">
				<ol role="list"
				    class="overflow-hidden lg:flex">

					<NavigationStep :status="stepStatus(1)" title="Getting Started"
					                desc="A few questions to help you get started" :sep="false"
					                :step="1" @click="stepNav(1)"/>
					<NavigationStep :status="stepStatus(2)" title="Design"
					                desc="Customize your Sensor Data slide." :step="2"
					                @click="stepNav(2)"/>
					<NavigationStep :status="stepStatus(3)" title="Finish"
					                desc="Download your customized slide." :step="3"
					                @click="stepNav(3)"/>

				</ol>
			</nav>
		</div>

		<div class="aspect-video bg-gray-50 h-full py-16 px-12">

			<fieldset
			    v-if="currentStep === 1"
			    class="w-3/6 h-full flex flex-col justify-center mx-auto">

				<div class="flex items-start py-6 mb-2 border-b">
					<div class="mr-4 text-sm">
						<span class="font-medium text-gray-700">
							Does your digital sensing product require an App or Hub to
							transmit data from the measurement tool to you?
						</span>
						<p>
							<button @click="showInfo(1)"
							        class="font-normal text-gray-400 underline hover:text-brand-dark hover:no-underline"
							        v-if="!isInfoShown(1)">More info...
							</button>
						</p>
						<div v-if="isInfoShown(1)" class="text-gray-500">
							<p>
								To map your sensor data flow, you need to know whether
								an App or Hub is required to transmit data.
							</p>
							<ul role="list" class="list-disc ml-4">
								<li>Contact your vendor partner to determine if an App
									or Hub is required
								</li>
								<li>Learn more about the sensor data measurement system
									starting <a
									    href="https://docs.google.com/presentation/d/1vBEa_ZBhutOCAVVZ2z5Qq8xG2uQ3y2B61LwMUQPJnmw/edit#slide=id.gccf2994462_0_1265"
									    target="_blank">here</a> in <a
									    href="https://playbook.dimesociety.org/"
									    target="_blank">The Playbook</a>.
								</li>
								<li>Plan for action item linking to work generated by
									this project that is not yet complete
								</li>
							</ul>
						</div>
					</div>
					<div class="flex mt-0.5">
						<div class="space-y-2">
							<div class="flex items-center">
								<input id="apphubtrue" name="apphub"
								       type="radio"
								       aria-describedby="Add App and Hub Column"
								       v-model="apphub"
								       value='true'
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="apphubtrue"
								       class="ml-1 block text-sm font-medium text-gray-700">
									Yes </label>
							</div>
							<div class="flex items-center">
								<input id="apphubfalse" name="apphub"
								       type="radio"
								       v-model="apphub"
								       value='false'
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="apphubfalse"
								       class="ml-1 block text-sm font-medium text-gray-700">
									No </label>
							</div>
						</div>
					</div>
				</div>
				<div class="flex items-start py-6 mb-2 border-b">
					<div class="mr-4 text-sm">
						<span class="font-medium text-gray-700">
							Does data generated by your digital sensing product flow through
							servers belonging to the manufacturer of the measurement tool?
						</span>
						<p>
							<button @click="showInfo(2)"
							        class="font-normal text-gray-400 underline hover:text-brand-dark hover:no-underline"
							        v-if="!isInfoShown(2)">More info...
							</button>
						</p>
						<div v-if="isInfoShown(2)" class="text-gray-500">
							<p>
								To map your sensor data flow, you need to know whether
								the manufacturer of your digital sensing product
								requires that the data flows through their servers.
							</p>
							<ul role="list" class="list-disc ml-4">
								<li>
									Contact your vendor partner to determine if the
									sensor generated data must flow through the
									manufacturers’ servers
								</li>
								<li>
									Learn more about the sensor data measurement
									system
									starting <a
								    href="https://docs.google.com/presentation/d/1vBEa_ZBhutOCAVVZ2z5Qq8xG2uQ3y2B61LwMUQPJnmw/edit#slide=id.gccf2994462_0_1265"
								    target="_blank">here</a> in <a
								    href="https://playbook.dimesociety.org/"
								    target="_blank">The Playbook</a>.
								</li>
								<li>
									Plan for action item linking to work generated
									by
									this project that is not yet complete
								</li>
							</ul>
						</div>
					</div>
					<div class="flex mt-0.5">
						<div class="space-y-2">
							<div class="flex items-center">
								<input id="manufacturertrue" name="manufacturer"
								       type="radio"
								       aria-describedby="Add Manufacturer's Servers"
								       v-model="manufacturer"
								       value='true'
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="manufacturertrue"
								       class="ml-1 block text-sm font-medium text-gray-700">
									Yes </label>
							</div>
							<div class="flex items-center">
								<input id="manufacturerfalse" name="manufacturer"
								       type="radio"
								       v-model="manufacturer"
								       value='false'
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="manufacturerfalse"
								       class="ml-1 block text-sm font-medium text-gray-700">
									No </label>
							</div>
						</div>
					</div>
				</div>
				<div class="flex items-start py-4 mb-4">
					<div class="mr-4 text-sm">
						<span class="font-medium text-gray-700">
							Does the data consumer perform filtering on the sensor generated
							data and store the data internally prior to performing analytics
							on the data and querying it?
						</span>
						<p>
							<button @click="showInfo(3)"
							        class="font-normal text-gray-400 underline hover:text-brand-dark hover:no-underline"
							        v-if="!isInfoShown(3)">More info...
							</button>
						</p>
						<div v-if="isInfoShown(3)" class="text-gray-500">
							<p>
								To map your sensor data flow, you need to know whether
								the data consumer will perform filtering on the sensor
								generated data and store the data locally.
							</p>
							<ul role="list" class="list-disc ml-4">
								<li>Contact your vendor partner to determine if the
									sensor generated data must flow through the
									manufacturers’ servers
								</li>
								<li>Learn more about the sensor data measurement system
									starting <a
									    href="https://docs.google.com/presentation/d/1vBEa_ZBhutOCAVVZ2z5Qq8xG2uQ3y2B61LwMUQPJnmw/edit#slide=id.gccf2994462_0_1265"
									    target="_blank">here</a> in <a
									    href="https://playbook.dimesociety.org/"
									    target="_blank">The Playbook</a>.
								</li>
								<li>Plan for action item linking to work generated by
									this project that is not yet complete
								</li>
							</ul>
						</div>
					</div>
					<div class="flex mt-0.5">
						<div class="space-y-2">
							<div class="flex items-center">
								<input id="analyticstrue" name="analytics"
								       type="radio"
								       aria-describedby="Add Manufacturer's Servers"
								       v-model="analytics"
								       value='true'
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="analyticstrue"
								       class="ml-1 block text-sm font-medium text-gray-700">
									Yes </label>
							</div>
							<div class="flex items-center">
								<input id="analyticsfalse" name="analytics"
								       type="radio"
								       v-model="analytics"
								       value='false'
								       class="focus:ring-brand h-4 w-4 text-brand-dark border-gray-300">
								<label for="analyticsfalse"
								       class="ml-1 block text-sm font-medium text-gray-700">
									No </label>
							</div>
						</div>
					</div>
				</div>
				<div class="flex flex-initial">
					<button @click="stepNav(2)"
					        class="bg-brand border border-transparent rounded-md shadow-sm py-2 px-4 inline-flex justify-center text-sm font-medium text-white hover:bg-brand-light focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-brand">
						Continue
					</button>
				</div>

			</fieldset>

			<div
			    v-if="currentStep === 2"
			    class="grid grid-flow-col auto-cols-max justify-evenly gap-0 h-full">
				<DigitalSensingProductsColumn/>
				<DividerArrow v-if="apphub === 'true'"/>
				<AppsHubsColumn v-if="apphub === 'true'"/>
				<DividerArrow/>
				<CentralizedColumn class="col-span-2"/>
				<DividerArrow v-if="manufacturer === 'true'"/>
				<ManufacturersColumn class="col-span-2" v-if="manufacturer === 'true'"/>
				<DividerArrow/>
				<FilteringStorageColumn/>
				<DividerArrow v-if="analytics === 'true'"/>
				<AnalyticsQueryingColumn v-if="analytics === 'true'"/>

			</div>

			<div v-if="currentStep === 3">
				TODO: Show Image and Download Button
			</div>
		</div>

	</main>


</template>

<script>
export default {
	name: 'DME App',
	data() {
		return {
			currentStep: 1,
			shownInfo: [],
			apphub: false,
			manufacturer: false,
			analytics: false,
		};
	},
	methods: {
		isInfoShown: function (step) {
			return this.shownInfo.includes(step);
		},
		showInfo: function (step) {
			if (this.shownInfo.includes(step)) {
				return false;
			}
			this.shownInfo.push(step);
		},
		stepNav: function (step) {
			this.currentStep = step
		},
		stepStatus: function (step) {

			if (step === this.currentStep) {
				return 'current'
			}

			// check if completed
			if (this.currentStep > step) {
				return 'completed'
			}

			return 'upcoming'
		}
	},
}
</script>
